from .mw_kie_gpt2 import (
    NODE_CLASS_MAPPINGS as KIE_GPT20_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as KIE_GPT20_NODE_DISPLAY_NAME_MAPPINGS,
)
from .mw_kuai_gpt2 import (
    NODE_CLASS_MAPPINGS as KUAI_GPT20_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as KUAI_GPT20_NODE_DISPLAY_NAME_MAPPINGS,
)


NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(KIE_GPT20_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(KIE_GPT20_NODE_DISPLAY_NAME_MAPPINGS)
NODE_CLASS_MAPPINGS.update(KUAI_GPT20_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(KUAI_GPT20_NODE_DISPLAY_NAME_MAPPINGS)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
