from .doubao_seedance20_zhenzhen_node import (
    NODE_CLASS_MAPPINGS as ZHENZHEN_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as ZHENZHEN_NODE_DISPLAY_NAME_MAPPINGS,
)
from .doubao_seedance20_duoyuan_node import (
    NODE_CLASS_MAPPINGS as DUOYUAN_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as DUOYUAN_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **ZHENZHEN_NODE_CLASS_MAPPINGS,
    **DUOYUAN_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **ZHENZHEN_NODE_DISPLAY_NAME_MAPPINGS,
    **DUOYUAN_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
